//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconOrchestrator.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountGroup
    {
        public int AccountGroupId { get; set; }
        public int AccountId { get; set; }
        public int GroupId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Group Group { get; set; }
    }
}
