//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconOrchestrator.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountTicket
    {
        public int AccounTicketId { get; set; }
        public int AccountId { get; set; }
        public int TicketId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
