//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconOrchestrator.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Detection()
        {
            this.DetectionTaxonomies = new HashSet<DetectionTaxonomy>();
            this.DnsRequests = new HashSet<DnsRequest>();
            this.DocumentsAccesses = new HashSet<DocumentsAccess>();
            this.DetectionTags = new HashSet<DetectionTag>();
            this.ExecutablesWrittens = new HashSet<ExecutablesWritten>();
            this.NetworkAccesses = new HashSet<NetworkAccess>();
            this.ScanResults = new HashSet<ScanResult>();
            this.DetectionTickets = new HashSet<DetectionTicket>();
        }
    
        public int DetectionId { get; set; }
        public string Name { get; set; }
        public System.DateTime Timestamp { get; set; }
        public Nullable<System.DateTime> ProcessStartTime { get; set; }
        public Nullable<System.DateTime> ProcessEndTime { get; set; }
        public string CommandLine { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
        public string FalconHostLink { get; set; }
        public string Description { get; set; }
        public string SHA256 { get; set; }
        public string MD5 { get; set; }
        public string SHA1 { get; set; }
        public Nullable<bool> AVDetections { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public int AccountId { get; set; }
        public int DetectionDeviceId { get; set; }
        public string Offset { get; set; }
        public string ProcessId { get; set; }
        public string ParentProcessId { get; set; }
        public int StatusId { get; set; }
        public int VendorSeverityId { get; set; }
        public int CustomerId { get; set; }
        public int CustomSeverityId { get; set; }
        public Nullable<int> ResponderId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual DetectionDevice DetectionDevice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetectionTaxonomy> DetectionTaxonomies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DnsRequest> DnsRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentsAccess> DocumentsAccesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetectionTag> DetectionTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExecutablesWritten> ExecutablesWrittens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NetworkAccess> NetworkAccesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScanResult> ScanResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetectionTicket> DetectionTickets { get; set; }
        public virtual Responder Responder { get; set; }
        public virtual Severity Severity { get; set; }
        public virtual Status Status { get; set; }
    }
}
