//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconOrchestrator.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetworkAccess
    {
        public int NetAccessId { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int AccessType { get; set; }
        public int ConnectionDirection { get; set; }
        public bool IsIPv6 { get; set; }
        public string LocalAddress { get; set; }
        public int LocalPort { get; set; }
        public string RemoteAddress { get; set; }
        public int RemotePort { get; set; }
        public string Protocol { get; set; }
        public int DetectionId { get; set; }
    
        public virtual Detection Detection { get; set; }
    }
}
