//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconOrchestrator.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponderSchedule
    {
        public int ScheduleId { get; set; }
        public string DayOfWeek { get; set; }
        public Nullable<int> ResponderId { get; set; }
    
        public virtual Responder Responder { get; set; }
    }
}
