//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconOrchestrator.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taxonomy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Taxonomy()
        {
            this.DetectionTaxonomies = new HashSet<DetectionTaxonomy>();
        }
    
        public int TaxonomyId { get; set; }
        public string Creator { get; set; }
        public string Description { get; set; }
        public System.DateTime Timestamp { get; set; }
        public bool Critical { get; set; }
        public string Value { get; set; }
        public int TaxTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetectionTaxonomy> DetectionTaxonomies { get; set; }
        public virtual TaxonomyType TaxonomyType { get; set; }
    }
}
