//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconOrchestrator.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.AccountTickets = new HashSet<AccountTicket>();
            this.DetectionTickets = new HashSet<DetectionTicket>();
            this.DeviceTickets = new HashSet<DeviceTicket>();
        }
    
        public int TicketId { get; set; }
        public string ExternalTicket { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> DispatchDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public int TicketRecipientId { get; set; }
        public string Comment { get; set; }
        public int SeverityId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountTicket> AccountTickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetectionTicket> DetectionTickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceTicket> DeviceTickets { get; set; }
        public virtual Severity Severity { get; set; }
        public virtual TicketRecipient TicketRecipient { get; set; }
    }
}
