//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconOrchestrator.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_DetectionAverages
    {
        public int Id { get; set; }
        public Nullable<int> Daily { get; set; }
        public Nullable<int> Weekly { get; set; }
        public Nullable<int> Monthly { get; set; }
    }
}
