//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconOrchestrator.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Whitelist
    {
        public int WhitelistId { get; set; }
        public string Creator { get; set; }
        public string Reason { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int WhitelistTypeId { get; set; }
        public string Value { get; set; }
    
        public virtual WhitelistType WhitelistType { get; set; }
    }
}
